language: node_js
sudo: required
cache:
  directories:
    - node_modules
node_js:
    - "12.2.0"
git:
  depth: 10
after_success:
  - 'npm run coveralls'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
