language: node_js
sudo: required
cache:
  directories:
    - node_modules
node_js:
    - "14.15.1"
git:
  depth: 10
before_install:
  - sudo apt-get update
  - 'npm install -g typescript'
  - 'npm install -g tslint'
after_success:
  - 'npm run coveralls'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
